name: Build & publish FreeBSD Executable

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build & publish FreeBSD Executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build package
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          sync: sshfs
          prepare: |
            pkg install -y node npm
            npm i
          run: |
            pkg --targets node18-freebsd-x64 .

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: pupflare
          tag_name: pupflare-x86_64-freebsd