name: Build & publish FreeBSD Executable

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-12
    name: Build & publish FreeBSD Executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build package
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          sync: sshfs
          mem: 2048
          prepare: |
            pkg install -y node npm sudo openssl-devel
          run: |
            sudo chmod -R 777 ./
            sudo chown -R $USER:$GROUP ~/.npm
            sudo chown -R $USER:$GROUP ~/.config
            sudo chown -R $USER:$GROUP ~/.cache
            sudo npm i
            npx pkg --targets node18-freebsd-x64 .

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: pupflare
          tag_name: pupflare-x86_64-freebsd