name: Build & publish FreeBSD Executable

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build & publish FreeBSD Executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install pnpm pkg -g
          pnpm i
          apt update
          apt install -y build-essential gcc-multilib freebsd-crossbuild-*

      - name: Build FreeBSD executable
        run: export CC=freebsd-x86_64-gcc && export export CXX=freebsd-x86_64-g++ && pkg --targets node18-freebsd-x64 .

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: pupflare
          tag_name: pupflare-x86_64-freebsd